### ISSUE TITLE
Kernel panic when hot unplug the keyboard on Surface Pro 7(Only macOS Ventura)

### ISSUE THREAD

**Issue by 368406148** [VoodooI2C/VoodooI2C#521] opened 2022-12-23 01:22 UTC
**Describe the bug**
The kernel of macOS Ventura panics when we hot unplug the keyboard from the machine.
 
**Did you read the common errors documentation?**
Yes

**Did you read the troubleshooting documentation?**
Yes

**Have you searched the issue on Github, Gitter, or Google?**
Yes

**System Environment**
Please answer:
1. macOS Ventura 13.1
2. Voodoo I2C I2CHID v2.7
3. Microsoft Surface Pro 7 i5-128-8G 1866

**Comment by kprinssu** [comment] 2022-12-23 13:05
Please use the GitHub issue template and attach a troubleshooting archive next time.


As well as searching Github for any existing issues a, this is most likely a duplicate of https://github.com/VoodooI2C/VoodooI2C/issues/507

**Closed** 2022-12-23 13:05 UTC
