### ISSUE TITLE
Crash at the login page after booting(MacOS 13 Ventura)

### ISSUE THREAD

**Issue by Leondrx0623** [VoodooI2C/VoodooI2C#519] opened 2022-12-03 14:54 UTC
**Describe the bug**
when use the voodool2C and voodool2CHID driver, system crash at the login page after booting. 

**Did you read the common errors documentation?**
yes

**Did you read the troubleshooting documentation?**
yes

**Have you searched the issue on Github, Gitter, or Google?**
yes

**System Environment**
Please answer:
1. What is your operating system? 
macos 13 Ventura 13.0.1

2. What version of the drivers (including drivers) are you using?
<img width="370" alt="image" src="https://user-images.githubusercontent.com/91593429/205446788-aefbeaf4-c52f-4477-9d02-6e94f616ec83.png">

3. What is your hardware configuration?
13600k-asus tuf b660m-6800xt

**Troubleshooting Archive**
<img width="910" alt="iShot_2022-12-03_22 32 46" src="https://user-images.githubusercontent.com/91593429/205446849-05b6d543-e50e-45f4-b6cf-311712bd07c5.png">

**Additional context**

**Comment by kprinssu** [comment] 2022-12-04 02:44
This is a duplicate of https://github.com/VoodooI2C/VoodooI2C/issues/507.

Please use the search feature before opening a new issue. As of right now, there is no fix but disable USB devices.

**Closed** 2022-12-04 02:45 UTC
