### ISSUE TITLE
Touchpad stop working after wake up from sleep

### ISSUE THREAD

**Issue by moishiteru** [VoodooI2C/VoodooI2C#558] opened 2024-10-21 22:33 UTC
**Describe the bug**
Touchpad stop working after wake up from sleep

**Did you read the common errors documentation?**
yes

**Did you read the troubleshooting documentation?**
yes

**Have you searched the issue on Github, Gitter, or Google?**
yes

**System Environment**
Please answer:
1. What is your operating system? 
Sequoia
2. What version of the drivers (including drivers) are you using?
 VoodooI2C.kext 2.8 version, VoodooPS2Controller.kext 2.35 version, VoodooI2CHID.kext version 1
3. What is your hardware configuration?
X540LA 
**Troubleshooting Archive**
[EFI X540LA.zip](https://github.com/user-attachments/files/17467512/EFI.X540LA.zip)

**Additional context**
EFI attached hope you can help me to resolve this issue

**Comment by kprinssu** [comment] 2024-10-22 01:15
You clearly have not read the troubleshooting documentation nor have you searched for existing issues. You have attached an improper troubleshooting archive.

This is a duplicate of https://github.com/VoodooI2C/VoodooI2C/issues/321

**Closed by kprinssu** 2024-10-22 01:15 UTC
