### ISSUE TITLE
Lenovo Xiaoxin Air14 2019Ryzen touchpad only has one finger, and there is no touchpad device in the settings, using GPI0 patch is invalid

### ISSUE THREAD

**Issue by Win10Q** [VoodooI2C/VoodooI2C#556] opened 2024-09-09 04:41 UTC
Lenovo Xiaoxin Air14 2019Ryzen touchpad only has one finger, and there is no touchpad device in the settings, using GPI0 patch is invalid

**Comment by Win10Q** [comment] 2024-09-09 04:47
if i use the actions latest，it will be panic

**Comment by kprinssu** [comment] 2024-09-09 12:47
I am closing this issue due to lack of troubleshooting archive and sounds like you know what the issue is.

The documentation on how to patch your DSDT is readily available on the README. Please use that to diagnose your configuration issue.

**Closed by kprinssu** 2024-09-09 12:47 UTC
